In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score

df = pd.read_csv("data/hexagon_sri_data.csv")

print(df.shape)
df.head()

(2004, 17)

,hex_id,raw_risk_score,population_density,center_lat,center_lon,crime_rate_per_1000,crime_SRI,log_crime_rate,geometry,dist_to_police_deg,dist_to_hospital_deg,dist_to_police_km,dist_to_hospital_km,police_access_SRI,hospital_access_SRI,access_SRI,final_SRI
0,8860144003fffff,1,101.273230,12.941812,77.358424,9.874278,321.288324,2.386400,POLYGON ((77.36258446529621 12.939310330965474...,0.127041,0.118651,14.101547,13.170271,528.885587,504.364921,516.625254,379.889403
1,8860144005fffff,1,97.508835,12.949251,77.371147,10.255481,326.047811,2.420855,"POLYGON ((77.3753083792728 12.946748757647693,...",0.117003,0.104930,12.987300,11.647196,486.917328,446.009508,466.463418,368.172493
2,8860144007fffff,2,101.273230,12.949274,77.362744,19.748555,410.534780,3.032477,"POLYGON ((77.36690549449615 12.94677147012535,...",0.124969,0.113263,13.871533,12.572226,520.222107,481.451312,500.836709,437.625358
3,8860144009fffff,1,115.839200,12.934306,77.370907,8.632656,304.540551,2.265159,POLYGON ((77.37506796308493 12.931802833610412...,0.113170,0.108130,12.561897,12.002384,470.894455,459.618266,465.256361,352.755294
4,886014400dfffff,2,116.242730,12.941767,77.375228,17.205377,392.472162,2.901717,POLYGON ((77.37938980381928 12.939264198176245...,0.110820,0.102167,12.300978,11.340584,461.066876,434.261941,447.664408,409.029836

In [2]:
import os
print(os.getcwd())
print(os.path.getmtime("data/hexagon_sri_data.csv"))

/Users/rashisingh/sentinel
1786980294.4711988

In [3]:
df = pd.read_csv("data/hexagon_sri_data.csv")
print(df.shape)
df.head()

(2004, 17)

,hex_id,raw_risk_score,population_density,center_lat,center_lon,crime_rate_per_1000,crime_SRI,log_crime_rate,geometry,dist_to_police_deg,dist_to_hospital_deg,dist_to_police_km,dist_to_hospital_km,police_access_SRI,hospital_access_SRI,access_SRI,final_SRI
0,8860144003fffff,1,101.273230,12.941812,77.358424,9.874278,321.288324,2.386400,POLYGON ((77.36258446529621 12.939310330965474...,0.127041,0.118651,14.101547,13.170271,528.885587,504.364921,516.625254,379.889403
1,8860144005fffff,1,97.508835,12.949251,77.371147,10.255481,326.047811,2.420855,"POLYGON ((77.3753083792728 12.946748757647693,...",0.117003,0.104930,12.987300,11.647196,486.917328,446.009508,466.463418,368.172493
2,8860144007fffff,2,101.273230,12.949274,77.362744,19.748555,410.534780,3.032477,"POLYGON ((77.36690549449615 12.94677147012535,...",0.124969,0.113263,13.871533,12.572226,520.222107,481.451312,500.836709,437.625358
3,8860144009fffff,1,115.839200,12.934306,77.370907,8.632656,304.540551,2.265159,POLYGON ((77.37506796308493 12.931802833610412...,0.113170,0.108130,12.561897,12.002384,470.894455,459.618266,465.256361,352.755294
4,886014400dfffff,2,116.242730,12.941767,77.375228,17.205377,392.472162,2.901717,POLYGON ((77.37938980381928 12.939264198176245...,0.110820,0.102167,12.300978,11.340584,461.066876,434.261941,447.664408,409.029836

In [4]:
# Features: jo cheezein model ko predict karne ke liye milengi
feature_cols = ['crime_rate_per_1000', 'population_density', 
                 'dist_to_police_km', 'dist_to_hospital_km']

X = df[feature_cols]
y = df['final_SRI']  # target: jo predict karna hai

# Train-test split (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Train size:", X_train.shape)
print("Test size:", X_test.shape)

Train size: (1603, 4)
Test size: (401, 4)

In [5]:
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [6]:
feature_cols = ['raw_risk_score', 'population_density', 
                 'dist_to_police_km', 'dist_to_hospital_km']

X = df[feature_cols]
y = df['final_SRI']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

print("Feature importances:")
for name, importance in zip(feature_cols, model.feature_importances_):
    print(f"  {name}: {importance:.3f}")

Feature importances:
  raw_risk_score: 0.316
  population_density: 0.560
  dist_to_police_km: 0.035
  dist_to_hospital_km: 0.089

In [7]:
y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Average Error (MAE):", mae)
print("R² Score:", r2)

Average Error (MAE): 11.516261778654224
R² Score: 0.9850899417127734

In [8]:
from sqlalchemy import create_engine

engine = create_engine('postgresql://rashisingh@localhost:5432/sentinel_db')
print("Connected!")

Connected!

In [9]:
df_to_load = df.rename(columns={'SRI': 'crime_sri', 'final_SRI': 'final_sri'})[
    ['hex_id', 'crime_rate_per_1000', 'population_density', 
     'dist_to_police_km', 'dist_to_hospital_km', 
     'crime_sri', 'access_SRI', 'final_sri']
].rename(columns={'access_SRI': 'access_sri'})

df_to_load.to_sql('hexagons', engine, if_exists='append', index=False, method='multi')
print("Loaded", len(df_to_load), "rows into database!")

KeyError: "['crime_sri'] not in index"